version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge
