name: Calculadora Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install --upgrade pip
      - name: Run unit tests
        run: |
          python -m unittest calculadoraTest.py
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-reports

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade setuptools
          pip install --upgrade pip
          pip install build
      - name: Build package
        run: python setup.py sdist bdist_wheel

  notification:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send email notification
        env:
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          echo "Pipeline executado!" | mail -s "Pipeline Status" $EMAIL_RECIPIENT

